const String generalPostQuery = r"""
                        query{
                          posts{
                            id
                            title
                            caption
                            pictureUrl
                            createdAt
                            updatedAt
                            viewers
                            dislikes{
                              id
                              username
                            }
                            user{
                              id
                              username
                            }
                          }
                        }
                      """;
